//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 11:01:35 AM MESZ 
//

package org.iviPro.editors.quiz.std;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Daten einer Antwort
 * 
 * <p>
 * Java class for TestAnswerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TestAnswerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="answerText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="position" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="isCorrekt" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestAnswerType", propOrder = {

})
public class TestAnswerType {

    @XmlElement(required = true)
    protected String answerText;
    @XmlAttribute(name = "Id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(required = true)
    protected int position;
    @XmlAttribute(required = true)
    protected boolean isCorrekt;

    /**
     * Gets the value of the answerText property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAnswerText() {
	return answerText;
    }

    /**
     * Sets the value of the answerText property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAnswerText(String value) {
	this.answerText = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the position property.
     * 
     */
    public int getPosition() {
	return position;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setPosition(int value) {
	this.position = value;
    }

    /**
     * Gets the value of the isCorrekt property.
     * 
     */
    public boolean isIsCorrekt() {
	return isCorrekt;
    }

    /**
     * Sets the value of the isCorrekt property.
     * 
     */
    public void setIsCorrekt(boolean value) {
	this.isCorrekt = value;
    }

}
