//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 11:01:35 AM MESZ 
//

package org.iviPro.editors.quiz.std;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Daten zur Bestimmung des nächsten Knotens
 * 
 * <p>
 * Java class for TestEdgeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TestEdgeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="targetId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="conditionLookback" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="conditionPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestEdgeType")
public class TestEdgeType {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String targetId;
    @XmlAttribute(required = true)
    protected int conditionLookback;
    @XmlAttribute(required = true)
    protected int conditionPoints;

    /**
     * Gets the value of the targetId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTargetId() {
	return targetId;
    }

    /**
     * Sets the value of the targetId property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTargetId(String value) {
	this.targetId = value;
    }

    /**
     * Gets the value of the conditionLookback property.
     * 
     */
    public int getConditionLookback() {
	return conditionLookback;
    }

    /**
     * Sets the value of the conditionLookback property.
     * 
     */
    public void setConditionLookback(int value) {
	this.conditionLookback = value;
    }

    /**
     * Gets the value of the conditionPoints property.
     * 
     */
    public int getConditionPoints() {
	return conditionPoints;
    }

    /**
     * Sets the value of the conditionPoints property.
     * 
     */
    public void setConditionPoints(int value) {
	this.conditionPoints = value;
    }

}
