//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 11:01:35 AM MESZ 
//

package org.iviPro.editors.quiz.std;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Eigenschaften und Einstellungen des Tests.
 * 
 * <p>
 * Java class for TestPropertiesType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TestPropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maxPoints" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="testTyp" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="evaluationMethod" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="timeOfFeedback" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestPropertiesType", propOrder = {

})
public class TestPropertiesType {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected String email;
    protected int maxPoints;
    protected int testTyp;
    protected int evaluationMethod;
    protected int timeOfFeedback;

    /**
     * Gets the value of the title property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTitle() {
	return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTitle(String value) {
	this.title = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCategory() {
	return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCategory(String value) {
	this.category = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAuthor() {
	return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAuthor(String value) {
	this.author = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEmail() {
	return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setEmail(String value) {
	this.email = value;
    }

    /**
     * Gets the value of the maxPoints property.
     * 
     */
    public int getMaxPoints() {
	return maxPoints;
    }

    /**
     * Sets the value of the maxPoints property.
     * 
     */
    public void setMaxPoints(int value) {
	this.maxPoints = value;
    }

    /**
     * Gets the value of the testTyp property.
     * 
     */
    public int getTestTyp() {
	return testTyp;
    }

    /**
     * Sets the value of the testTyp property.
     * 
     */
    public void setTestTyp(int value) {
	this.testTyp = value;
    }

    /**
     * Gets the value of the evaluationMethod property.
     * 
     */
    public int getEvaluationMethod() {
	return evaluationMethod;
    }

    /**
     * Sets the value of the evaluationMethod property.
     * 
     */
    public void setEvaluationMethod(int value) {
	this.evaluationMethod = value;
    }

    /**
     * Gets the value of the timeOfFeedback property.
     * 
     */
    public int getTimeOfFeedback() {
	return timeOfFeedback;
    }

    /**
     * Sets the value of the timeOfFeedback property.
     * 
     */
    public void setTimeOfFeedback(int value) {
	this.timeOfFeedback = value;
    }

}
